### ISSUE TITLE
south: orm['fooapp.MyChildModel'] does not exist

### ISSUE THREAD

**Issue by guettli** [craigds/django-typed-models#25]
south freezed db-schema stored in the variable "orm" does not contain the ChildModel.

I solved it like this:
 ```
               orm['foo.ParentModel'].objects.get_or_create(
                    type='foo.mychildmodel',
                    ...)

```

**Comment by craigds** [comment]
Closing this, not going to support south now. If there are similar issues with core migrations (it wouldn't surprise me) please reopen another ticket :)

**Comment by guettli** [comment]
ok
