### ISSUE TITLE
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

### ISSUE THREAD

**Issue by davidcroda** [craigds/django-typed-models#27]
Is this compatible with the django 1.8? I have tried numerous settings but cannot get the example listed in the readme to work.  The main issue seems to be that you cannot reference the base typed model from its subclasses within models.py.

Here is the full traceback: https://gist.github.com/davidcroda/ac493a0ad367a56aa977#file-gistfile1-txt-L18

This is a fresh django project, with a single app, using the example models.py from the readme.

**Comment by guettli** [comment]
the exception means that a django.setup() call is missing.

**Comment by craigds** [comment]
Seems it's not django 1.8 compatible yet. I can't speak to the specific problem, but the tests fail when run on django 1.8 too (it doesn't hit this problem, because `runtests.py` calls `django.setup()`)

**Comment by davidcroda** [comment]
@guettli I am not sure that is the case. All I did was create a default project and app, copy the example from the readme, and call python manage.py runserver.  I don't believe you need to call django.setup() when using manage.py, but I am a django beginner so I very well could be wrong.

Thanks for the info @craigds. As mentioned I am pretty new to django but if I am able to update this for 1.8 I will be sure to put in a pull request. Thanks!

**Comment by guettli** [comment]
@davidcroda I have seen this stacktrace very often during the last days. We are upgrading from Django1.6 to 1.7. Calling `django.setup()` needs to be done for console scripts. It helped in my cases. But my console scripts were not a sub command from manage.py. I guess you are right. If you run commands via manage.py there should be no need to call django.setup(). AFAIK this is handled in manage.py.

**Comment by kriestof** [comment]
Looks like this is caused by to introducing Model api in 1.8. Actually AppRegistryNotReady is thrown when typed models tries to execute ```_meta.get_fields_with_model```.

https://docs.djangoproject.com/en/1.8/ref/models/meta/
