### ISSUE TITLE
Broken subclass functionality with "objects"

### ISSUE THREAD

**Issue by cdobbyn** [craigds/django-typed-models#32]
After commit: 7b505666350278a9f4f8fe0150293410ec0f87ce

By my recommendation we hard-coded "objects" attribute as Django documentation appeared to make this seem necessary.

Example:
`class Exhibitored(TypedModel, PublishModel):`

Where PublishModel is overriding the objects manager and TypedModel due to our code now overwrites that same manager.

It appears we could have got around this by modifying _default manager on cls.__class__. Will submit a pull request with the suggested fix.

**Comment by craigds** [comment]
I could be wrong, but I don't think there's a sane way to fix this in third-party apps when using Django 1.10+. If you need to override `objects` then you need to make a new manager which is a subclass of `TypedModelManager`:

```python
class ExhibitManager(PublishManager, TypedModelManager):
    pass

class Exhibitored(TypedModel, PublishModel):
    ...
    objects = ExhibitManager()
```

Changing `cls.__class__._default_manager` doesn't sound right (I think that's `ModelBase._default_manager` - changing it would affect every model class in the project)

**Comment by cdobbyn** [comment]
Should be good now in pull request #33, but it could use some peer review. I have tested myself and it appears to work as expected inheriting any additional "objects" if they exist. TravisCI is happy.

**Comment by sloria** [comment]
As of #37, custom managers for `TypedModel` subclasses must explicitly subclass `TypedModelManager` (as in @craigds's [comment above](https://github.com/craigds/django-typed-models/issues/32#issuecomment-293124789). So I don't think any further action is needed on this issue. Close?

**Comment by craigds** [comment]
yep. thanks
