### ISSUE TITLE
admin integration

### ISSUE THREAD

**Issue by olivierdalang** [craigds/django-typed-models#49]
Just testing out the app, looks very useful.

Out of the box, it's a bit counter intuitive when adding child classes in django admin because "type" field appears as a select. This means you click on "Add a new Feline" and then you need to select Feline again.

Would it be an option to hack "editable=False" in the child classes fields, so that the select doesn't appear by default ? Alternatively, a ModelAdmin mixin could be included in the app to deal with this.

**Comment by craigds** [comment]
^ done
