### ISSUE TITLE
Django 3 support and package maintenance?

### ISSUE THREAD

**Issue by barclaey** [craigds/django-typed-models#55]
Hi,

I was wondering if this project is still maintained, I noticed pull requests have not been merged for quite some time and a lot of (very) old issues are not being closed.

Also this package is not compatible anymore with Django 3 since Django 3 dropped build-in support for django.utils.six

I think this project is great work, the only way holding me back in using it in my projects is the low activity. It would be nice to get a little insight about the future plans on this package.

**Comment by craigds** [comment]
I'm still using this project in my day job; IMO it's very stable and so low activity isn't a bad thing. I haven't used django 3 yet, so this is the first I've heard of it being broken.

I'll make some effort to go through and close the older issues. Many of them are feature requests, which would be accepted if someone who wants them enough will spend time implementing them.

**Comment by barclaey** [comment]
Hi, thanks for the quick reply and swift action :-)
I saw you bumped the version to 0.10.0 👍 , would it be possible to make a new release for that version?

This package seems indeed stable, so don't be too modest to put the package on production/stable in stead of beta (https://djangopackages.org/grids/g/model-inheritance/). But that's a personal choice of course :-)

**Comment by craigds** [comment]
For now it is beta. I do plan to do some breaking changes at some stage. At that point I'll update the version number to 1.0 and call it stable.

Yep I'll release a 0.10 now
